
version: 2

models:
  - name: source_data_quality
    description: "A starter dbt model"
    columns:
      - name: actor_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null