global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-webserver:8080']
  - job_name: 'airflow_statsd_exporter'
    static_configs:
      - targets: ['statsd_exporter:9102']